repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: '\.ipynb$'
        stages: [commit]
        language: system
        entry: bash -c 'conda run -n practice_env python -m nbconvert --ClearOutputPreprocessor.enabled=True --inplace "$@"' --
        pass_filenames: true
